# Generated by Django 6.0.7 on 2026-08-24 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_projectimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='show_on_homepage',
            field=models.BooleanField(default=False, verbose_name="Projet visible sur la page d'accueil"),
        ),
    ]
