# Generated by Django 6.0.7 on 2026-08-24 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_project_show_on_homepage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={},
        ),
        migrations.RemoveField(
            model_name='project',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='project',
            name='updated_at',
        ),
    ]
