# Generated by Django 6.0.7 on 2026-08-25 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_project_options_remove_project_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='conception',
            field=models.TextField(blank=True, verbose_name='02 — La conception'),
        ),
        migrations.AddField(
            model_name='project',
            name='idea',
            field=models.TextField(blank=True, verbose_name="01 — L'idée"),
        ),
        migrations.AddField(
            model_name='project',
            name='realisation',
            field=models.TextField(blank=True, verbose_name='03 — La réalisation'),
        ),
        migrations.AddField(
            model_name='project',
            name='resultat',
            field=models.TextField(blank=True, verbose_name='04 — Le résultat'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(verbose_name='À propos du projet'),
        ),
    ]
