# Generated by Django 6.0.7 on 2026-09-13 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_project_conception_project_idea_project_realisation_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Projet', 'verbose_name_plural': 'Projets'},
        ),
        migrations.AddField(
            model_name='project',
            name='homepage_order',
            field=models.PositiveIntegerField(default=0, verbose_name="Ordre sur la page d'accueil"),
        ),
    ]
