# Generated by Django 6.0.7 on 2026-09-13 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_alter_project_options_project_homepage_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Ordre dans les projets'),
        ),
    ]
