# Generated by Django 6.0.7 on 2026-09-13 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_project_project_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageProjectOrder',
            fields=[
            ],
            options={
                'verbose_name': "Ordre d'affichage Accueil",
                'verbose_name_plural': "Ordre d'affichage Accueil",
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('projects.project',),
        ),
        migrations.CreateModel(
            name='ProjectPageOrder',
            fields=[
            ],
            options={
                'verbose_name': "Ordre d'affichage Projet",
                'verbose_name_plural': "Ordre d'affichage Projet",
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('projects.project',),
        ),
    ]
