# Generated by Django 6.0.7 on 2026-08-27 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('electronique', 'Électronique'), ('randonnee', 'Randonnée')], max_length=20, verbose_name='Catégorie')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('short_description', models.TextField(blank=True, verbose_name='Description courte')),
                ('content', models.TextField(verbose_name='Contenu')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='articles/thumbnails/', verbose_name='Image principale')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de publication')),
                ('is_published', models.BooleanField(default=False, verbose_name='Publié')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Mettre en avant')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
