# Generated by Django 6.0.7 on 2026-08-25 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hiking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Nom')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Lieu')),
                ('massif', models.CharField(blank=True, max_length=200, verbose_name='Massif / secteur')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('short_description', models.TextField(blank=True, verbose_name='Description courte')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('distance', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Distance (km)')),
                ('elevation_gain', models.PositiveIntegerField(blank=True, null=True, verbose_name='Dénivelé positif (m)')),
                ('max_altitude', models.PositiveIntegerField(blank=True, null=True, verbose_name='Altitude maximale (m)')),
                ('duration', models.DurationField(blank=True, null=True, verbose_name='Durée')),
                ('difficulty', models.CharField(blank=True, choices=[('facile', 'Facile'), ('moderee', 'Modérée'), ('difficile', 'Difficile'), ('tres_difficile', 'Très difficile')], max_length=20, verbose_name='Difficulté')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='hiking/thumbnails/', verbose_name='Image principale')),
                ('gpx_url', models.URLField(blank=True, verbose_name='Lien GPX')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Mettre en avant')),
                ('is_published', models.BooleanField(default=True, verbose_name='Publié')),
            ],
        ),
        migrations.CreateModel(
            name='HikingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hiking/gallery/', verbose_name='Image')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Légende')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('hiking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='hiking.hiking', verbose_name='Randonnée')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
