# Generated by Django 6.0.7 on 2026-08-25 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hiking',
            name='equipment',
            field=models.TextField(blank=True, help_text='Liste des équipements utilisés lors de cette randonnée.', verbose_name='Équipements'),
        ),
    ]
