# Generated by Django 6.0.7 on 2026-08-25 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiking', '0002_hiking_equipment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('image', models.ImageField(blank=True, null=True, upload_to='equipment/', verbose_name='Image')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
        ),
        migrations.RemoveField(
            model_name='hiking',
            name='equipment',
        ),
        migrations.AddField(
            model_name='hiking',
            name='equipment',
            field=models.ManyToManyField(blank=True, related_name='hikings', to='hiking.equipment', verbose_name='Équipements'),
        ),
    ]
